#' Paramounter part2
#'
#' Optimize XCMS parameters by paramounter part2. Provide all parameters.
#' @return A ggplot object of missing value.
#' @param directory The data path for mzXML files.
#' @param massSDrange The range of standard deviations for mass differences, default value is 2 (95% confidence interval).
#' @param smooth Chromatographic smoothness, default value is 0. For full scan data, use a positive value; for example, use smooth = 4 for a 4 Hz spectral rate.
#' @param cutoff The ppm percentage for determining the cutoff line of mass accuracy distribution, default value is 0.95 (95%).
#' @param ppmCut generated by paramounter_part1
#' @param thread number of thread
#' @importFrom future plan availableCores multisession
#' @importFrom dplyr bind_rows filter
#' @importFrom furrr future_map
#' @import ggplot2
#' @importFrom MSnbase readMSData mz intensity rtime
#' @importFrom plotly ggplotly plot_ly add_trace layout
#' @references see https://github.com/HuanLab/Paramounter
#' @description
#' Research paper: https://pubs.acs.org/doi/10.1021/acs.analchem.1c04758
#' DOI:10.1021/acs.analchem.1c04758
#'
#'
#' @noRd
#' @export
#'
paramounter_part2 = function(
    directory,
    massSDrange = 2,
    smooth = 0,
    cutoff = 0.95,
    filenum = c(3,5,"all"),
    thread,
    ppmCut
) {
  # filenum = match.arg(filenum)
  filename <- list.files(path = directory,pattern = ".mzXML")
  start_time <- Sys.time()
  mzDiff <- c()
  ppm <- c()
  noiselevel <- c()
  peakWidth <- c()
  peakScans <- c()
  SNRatio <- c()
  peakHeight <- c()
  massShiftALL <- c()
  rtShiftALL <- c()
  mzDiff2D <- as.data.frame(matrix(ncol = 3, nrow = 1))
  colnames(mzDiff2D) <- c("mz", "rt", "mzdiff")
  ppm2D <- as.data.frame(matrix(ncol = 3, nrow = 1))
  colnames(ppm2D) <- c("mz", "rt", "ppm")
  Shift <- as.data.frame(matrix(ncol = 3, nrow = 1))
  colnames(Shift) <- c("mz", "rt", "Sample")

  #smoothing function
  peak_smooth <- function(x,level=smooth){
    n <- level
    if(length(x) < 2*n){
      return(x)
    } else if(length(unique(x))==1){
      return(x)
    } else{
      y <- vector(length=length(x))
      for(i in 1:n){
        y[i] <- sum(c((n-i+2):(n+1),n:1)*x[1:(i+n)])/sum(c((n-i+2):(n+1),n:1))
      }
      for(i in (n+1):(length(y)-n)){
        y[i] <-  sum(c(1:(n+1),n:1)*x[(i-n):(i+n)])/sum(c(1:(n+1),n:1))
      }
      for(i in (length(y)-n+1):length(y)){
        y[i] <- sum(c(1:n,(n+1):(n+i-length(x)+1))*x[(i-n):length(x)])/sum(c(1:n,(n+1):(n+i-length(x)+1)))
      }
      return(y)
    }
  }

  #process function
  process_file <- function(file,q) {
    ms1data <- readMSData(files = file.path(directory,file[q]), mode = "onDisk", msLevel. = 1)
    mzRange <- c(min(unlist(mz(ms1data))), max(unlist(mz(ms1data))))
    ROI <- seq(mzRange[1], mzRange[2], 0.05)
    mzData <- mz(ms1data)
    intData <- intensity(ms1data)
    rtime <- rtime(ms1data)
    snALL <- c()
    sALL <- c()
    peakWidthALL <- c()
    peakScansALL <- c()
    ShiftTable <- as.data.frame(matrix(ncol = 3, nrow = 1))
    colnames(ShiftTable) <- c("mz", "rt", "Sample")
    ppm2Ddist <- as.data.frame(matrix(ncol = 3, nrow = 1))
    colnames(ppm2Ddist) <- c("mz", "rt", "ppm")
    mzdiff2Ddist <- as.data.frame(matrix(ncol = 3, nrow = 1))
    colnames(mzdiff2Ddist) <- c("mz", "rt", "mzdiff")
    noiseALL <- c()

    # ROI detection and universal parameter estimation
    split_res_list =  furrr::future_map(.x = c(1:(length(ROI) - 1)),.f = function(.x) {
      i = .x

      blank_list = list(ppm2Ddist = ppm2Ddist,
                        mzdiff2Ddist = mzdiff2Ddist,
                        peakWidthALL = peakWidthALL,
                        peakScansALL = peakScansALL,
                        snALL = snALL,
                        sALL = sALL,
                        ShiftTable = ShiftTable,
                        noiseALL = noiseALL)

      currmzRange <- c(ROI[i], ROI[i+1])
      tmpMZdata <- mzData
      tmpINTdata <- intData
      for (j in 1:length(mzData)) {
        index <- which(tmpMZdata[[j]] >= currmzRange[1] & tmpMZdata[[j]] < currmzRange[2])
        tmpMZdata[[j]] <- tmpMZdata[[j]][index]
        tmpINTdata[[j]] <- tmpINTdata[[j]][index]
      }
      # Extract the intensity vectors from each m/z bin
      eicINTraw <- c()
      eicINT <- c()
      eicRT <- c()
      for (k in 1:length(mzData)) {
        if (length(tmpINTdata[[k]]) > 0) {
          eicINTraw[k] <- mean(tmpINTdata[[k]])
        } else {
          eicINTraw[k] <- 0
        }
        eicRT[k] <- rtime[k]
      }
      if (sum(eicINTraw != 0) == 0) return(blank_list)
      # Sort the intensity vectors from each m/z bin, estimate the noise cut off and average
      eicINT <- peak_smooth(eicINTraw)
      eicNon0 <- sort(eicINT[eicINT > 0])
      if (length(eicNon0) > 10) {
        for (x in seq(10, length(eicNon0), 10)) {
          sd <- sd(eicNon0[1:x])
          blk <- sum(eicNon0[1:x])/x
          thres <- blk + 3*sd
          if (x+1 <= length(eicNon0)) {
            if (eicNon0[x+1] >= thres) break()
          }
        }
        cutOFF <- eicNon0[x]
      } else {
        cutOFF <- max(eicNon0)
        sd <- 0
        blk <- 0
      }
      noiseALL[i] <- cutOFF

      # Find the Reference m/z in each ROI from each m/z bin
      aboveTHindex <- which(eicINT > cutOFF)
      if (length(aboveTHindex) == 0) return(blank_list)
      candidateSegInd <- split(aboveTHindex, cumsum(c(1, diff(aboveTHindex) != 1)))
      peakInd <- c()
      for (x in 1:length(candidateSegInd)) {
        peakInd[x] <- which(eicINT[candidateSegInd[[x]]] == max(eicINT[candidateSegInd[[x]]]))[1] + min(candidateSegInd[[x]]) - 1
      }
      refMZvec <- c()
      for (y in 1:length(peakInd)) {
        highestINT <- which(tmpINTdata[[peakInd[y]]] == max(tmpINTdata[[peakInd[y]]]))[1]
        refMZvec[y] <- tmpMZdata[[peakInd[y]]][highestINT]
      }

      # Estimate the universal parameters (mass tolerance, peak height, and peak width) for each m/z bin
      for (z in 1:length(peakInd)) {
        currPeakInd <- peakInd[z]
        currRefMz <- refMZvec[z]
        currSamePeakMass <- c()
        currSamePeakMass <- c(currSamePeakMass, currRefMz)
        leftInd <- currPeakInd-1
        rightInd <- currPeakInd+1
        if (leftInd > 0) {
          while (length(tmpMZdata[[leftInd]]) > 0 & mean(tmpINTdata[[leftInd]]) >= cutOFF) {
            if (length(tmpMZdata[[leftInd]]) == 1) {
              currSamePeakMass <- c(currSamePeakMass, tmpMZdata[[leftInd]])
              if (eicINT[leftInd] > eicINT[leftInd+1] & length(currSamePeakMass) > 5) {
                Q1 <- as.numeric(summary(currSamePeakMass)[2])
                Q3 <- as.numeric(summary(currSamePeakMass)[5])
                LB <- Q1 - 1.5 *(Q3 - Q1)
                RB <- Q3 + 1.5 *(Q3 - Q1)
                if (currSamePeakMass[length(currSamePeakMass)] < LB || currSamePeakMass[length(currSamePeakMass)] > RB) break()
              }
            } else {
              abvector <- abs(tmpMZdata[[leftInd]] - currRefMz)
              NearInd <- which(abvector == min(abvector))[1]
              currSamePeakMass <- c(currSamePeakMass, tmpMZdata[[leftInd]][NearInd])
              if (eicINT[leftInd] > eicINT[leftInd+1] & length(currSamePeakMass) > 5) {
                Q1 <- as.numeric(summary(currSamePeakMass)[2])
                Q3 <- as.numeric(summary(currSamePeakMass)[5])
                LB <- Q1 - 1.5 *(Q3 - Q1)
                RB <- Q3 + 1.5 *(Q3 - Q1)
                if (currSamePeakMass[length(currSamePeakMass)] < LB || currSamePeakMass[length(currSamePeakMass)] > RB) break()
              }
            }
            leftInd <- leftInd-1
            if (leftInd <= 0) break()
          }
        }
        if (rightInd <= length(tmpMZdata)) {
          while (length(tmpMZdata[[rightInd]]) > 0 & mean(tmpINTdata[[rightInd]]) >= cutOFF) {
            if (length(tmpMZdata[[rightInd]]) == 1) {
              currSamePeakMass <- c(currSamePeakMass, tmpMZdata[[rightInd]])
              if (eicINT[rightInd] > eicINT[rightInd-1] & length(currSamePeakMass) > 5) {
                Q1 <- as.numeric(summary(currSamePeakMass)[2])
                Q3 <- as.numeric(summary(currSamePeakMass)[5])
                LB <- Q1 - 1.5 *(Q3 - Q1)
                RB <- Q3 + 1.5 *(Q3 - Q1)
                if (currSamePeakMass[length(currSamePeakMass)] < LB || currSamePeakMass[length(currSamePeakMass)] > RB) break()
              }
            } else {
              abvector <- abs(tmpMZdata[[rightInd]] - currRefMz)
              NearInd <- which(abvector == min(abvector))[1]
              currSamePeakMass <- c(currSamePeakMass, tmpMZdata[[rightInd]][NearInd])
              if (eicINT[rightInd] > eicINT[rightInd-1] & length(currSamePeakMass) > 5) {
                Q1 <- as.numeric(summary(currSamePeakMass)[2])
                Q3 <- as.numeric(summary(currSamePeakMass)[5])
                LB <- Q1 - 1.5 *(Q3 - Q1)
                RB <- Q3 + 1.5 *(Q3 - Q1)
                if (currSamePeakMass[length(currSamePeakMass)] < LB || currSamePeakMass[length(currSamePeakMass)] > RB) break()
              }
            }
            rightInd <- rightInd+1
            if (rightInd > length(tmpMZdata)) break()
          }
        }
        if (sum(is.na(currSamePeakMass)) > 0) next()
        if (length(currSamePeakMass) > 1 && length(currSamePeakMass) < 200) {
          ppmCheck <- (massSDrange*sd(currSamePeakMass))/currRefMz * 1e6
          if (ppmCheck < ppmCut) {
            daDiff <- massSDrange*sd(currSamePeakMass)
            ppmDiff <- (massSDrange*sd(currSamePeakMass))/currRefMz * 1e6
            currPeakWidth <- rtime[[rightInd - 1]] - rtime[[leftInd + 1]]
            currPeakScans <- rightInd - leftInd
            ppm2Ddist <- rbind(ppm2Ddist, c(currRefMz, rtime[[peakInd[z]]], ppmDiff))
            mzdiff2Ddist <- rbind(mzdiff2Ddist, c(currRefMz, rtime[[peakInd[z]]], daDiff))
            peakWidthALL <- c(peakWidthALL, currPeakWidth)
            peakScansALL <- c(peakScansALL, currPeakScans)
            if (cutOFF > 0) {
              snALL <- c(snALL, (eicINT[currPeakInd]-blk)/sd)
            } else {
              snALL <- c(snALL, eicINT[currPeakInd])
            }
            sALL <- c(sALL, eicINT[currPeakInd])
            if (z == 1) {
              if (is.na(peakInd[z+1])) {
                ShiftTable <- rbind(ShiftTable, c(currRefMz, rtime[[currPeakInd]], q))
              }
              if (!is.na(peakInd[z+1])) {
                if (rtime[[currPeakInd]] < (rtime[[peakInd[z+1]]] - 300)) {
                  ShiftTable <- rbind(ShiftTable, c(currRefMz, rtime[[currPeakInd]], q))
                }
              }
            }
            if (z > 1) {
              if (is.na(peakInd[z+1]) & rtime[[currPeakInd]] > (rtime[[peakInd[z-1]]] + 300)) {
                ShiftTable <- rbind(ShiftTable, c(currRefMz, rtime[[currPeakInd]], q))
              }
              if (!is.na(peakInd[z+1])) {
                if (rtime[[currPeakInd]] < (rtime[[peakInd[z+1]]] - 300)) {
                  ShiftTable <- rbind(ShiftTable, c(currRefMz, rtime[[currPeakInd]], q))
                }
              }
            }
          }
        }
      }
      final_list = list(ppm2Ddist = ppm2Ddist,
                        mzdiff2Ddist = mzdiff2Ddist,
                        peakWidthALL = peakWidthALL,
                        peakScansALL = peakScansALL,
                        snALL = snALL,
                        sALL = sALL,
                        ShiftTable = ShiftTable,
                        noiseALL = noiseALL)
      return(final_list)
    },.progress = T)

    final_result = list(
      ppm2Ddist = dplyr::bind_rows(lapply(split_res_list, function(x) x$ppm2Ddist)) %>% dplyr::filter(!is.na(mz)),
      mzdiff2Ddist = dplyr::bind_rows(lapply(split_res_list, function(x) x$mzdiff2Ddist)) %>% dplyr::filter(!is.na(mz)),
      peakWidthALL = unlist(lapply(split_res_list, function(x) x$peakWidthALL), use.names = FALSE),
      peakScansALL = unlist(lapply(split_res_list, function(x) x$peakScansALL), use.names = FALSE),
      snALL = unlist(lapply(split_res_list, function(x) x$snALL), use.names = FALSE),
      sALL = unlist(lapply(split_res_list, function(x) x$sALL), use.names = FALSE),
      ShiftTable = dplyr::bind_rows(lapply(split_res_list, function(x) x$ShiftTable)) %>% dplyr::filter(!is.na(mz)),
      noiseALL = unlist(lapply(split_res_list, function(x) x$noiseALL), use.names = FALSE)
    )
    return(final_result)
  }

  #parallel run
  if((Sys.info())[1] == "Linux") {
    plan(multicore, workers = thread)
  } else {
    plan(multisession, workers = thread)
  }


  results <- purrr::map(.x = 1:filenum, .f = function(.x) {process_file(file = filename,q = .x)})

  # extract parameters
  ppm2D <- do.call(rbind, lapply(results, function(x) x$ppm2Ddist))
  mzDiff2D <- do.call(rbind, lapply(results, function(x) x$mzdiff2Ddist))
  peakWidth <- unlist(lapply(results, function(x) x$peakWidthALL))
  peakScans <- unlist(lapply(results, function(x) x$peakScansALL))
  SNRatio <- unlist(lapply(results, function(x) x$snALL))
  peakHeight <- unlist(lapply(results, function(x) x$sALL))
  Shift <- do.call(rbind, lapply(results, function(x) x$ShiftTable))
  noiselevel <- unlist(lapply(results, function(x) x$noiseALL))
  # Estimation of the instrumental shift parameters
  if (length(filename) > 1) {
    Shift <- Shift[complete.cases(Shift),]
    Shiftlist <- split(Shift, Shift[,3])
    if (length(Shiftlist) < 3){
      AlignmentT1 <- data.frame(matrix(nrow = 0, ncol = (ncol(Shiftlist[[1]]) + ncol(Shiftlist[[2]]))))
      for(i in 1:nrow(Shiftlist[[1]])){
        mass.lower.limit <- as.numeric(Shiftlist[[1]]$mz[i]) - 0.015
        mass.upper.limit <- as.numeric(Shiftlist[[1]]$mz[i]) + 0.015
        rt.lower.limit <- as.numeric(Shiftlist[[1]]$rt[i]) - 30
        rt.upper.limit <- as.numeric(Shiftlist[[1]]$rt[i]) + 30
        temp <- Shiftlist[[2]][(as.numeric(Shiftlist[[2]]$mz) >= as.numeric(mass.lower.limit) &
                                  as.numeric(Shiftlist[[2]]$mz) <= as.numeric(mass.upper.limit) &
                                  as.numeric(Shiftlist[[2]]$rt) >= as.numeric(rt.lower.limit) &
                                  as.numeric(Shiftlist[[2]]$rt) <= as.numeric(rt.upper.limit)),]
        temp <- temp[complete.cases(temp),]
        if(nrow(temp) > 0) {
          AlignmentT1 <- rbind(AlignmentT1, c(Shiftlist[[1]][i,], temp[1,]))
        }
      }
      AlignmentT1 <- AlignmentT1[complete.cases(AlignmentT1),]
      colnames(AlignmentT1) <- c(colnames(Shiftlist[[1]]), colnames(Shiftlist[[2]]))
    } else {
      AlignmentT1 <- data.frame(matrix(nrow = 0, ncol = (ncol(Shiftlist[[1]]) + ncol(Shiftlist[[2]]))))
      for(i in 1:nrow(Shiftlist[[1]])){
        mass.lower.limit <- as.numeric(Shiftlist[[1]]$mz[i]) - 0.015
        mass.upper.limit <- as.numeric(Shiftlist[[1]]$mz[i]) + 0.015
        rt.lower.limit <- as.numeric(Shiftlist[[1]]$rt[i]) - 30
        rt.upper.limit <- as.numeric(Shiftlist[[1]]$rt[i]) + 30
        temp <- Shiftlist[[2]][(as.numeric(Shiftlist[[2]]$mz) >= as.numeric(mass.lower.limit) &
                                  as.numeric(Shiftlist[[2]]$mz) <= as.numeric(mass.upper.limit) &
                                  as.numeric(Shiftlist[[2]]$rt) >= as.numeric(rt.lower.limit) &
                                  as.numeric(Shiftlist[[2]]$rt) <= as.numeric(rt.upper.limit)),]
        temp <- temp[complete.cases(temp),]
        if(nrow(temp) > 0) {
          AlignmentT1 <- rbind(AlignmentT1, c(Shiftlist[[1]][i,], temp[1,]))
        }
      }
      AlignmentT1 <- AlignmentT1[complete.cases(AlignmentT1),]
      colnames(AlignmentT1) <- c(colnames(Shiftlist[[1]]), colnames(Shiftlist[[2]]))

      for(k in 3:length(Shiftlist)){
        output <- data.frame(matrix(nrow = 0, ncol = ncol(AlignmentT1) + ncol(Shiftlist[[k]])))
        for(j in 1:nrow(AlignmentT1)){
          mass.lower.limit <- as.numeric(AlignmentT1[j,1]) - 0.015
          mass.upper.limit <- as.numeric(AlignmentT1[j,1]) + 0.015
          rt.lower.limit <- as.numeric(AlignmentT1[j,2]) - 30
          rt.upper.limit <- as.numeric(AlignmentT1[j,2]) + 30
          temp <- Shiftlist[[k]][(as.numeric(Shiftlist[[k]]$mz) >= as.numeric(mass.lower.limit) &
                                    as.numeric(Shiftlist[[k]]$mz) <= as.numeric(mass.upper.limit) &
                                    as.numeric(Shiftlist[[k]]$rt) >= as.numeric(rt.lower.limit) &
                                    as.numeric(Shiftlist[[k]]$rt) <= as.numeric(rt.upper.limit)),]
          temp <- temp[complete.cases(temp),]
          if(nrow(temp) > 0) {
            tmprow <- cbind(AlignmentT1[j,], temp[1,])
            colnames(tmprow) <- colnames(output)
            output <- rbind(output, tmprow)
          }
        }
        colnames(output) <- c(colnames(AlignmentT1), colnames(Shiftlist[[k]]))
        AlignmentT1 <- data.frame(matrix(nrow = 0, ncol = ncol(output)))
        AlignmentT1 <- output[complete.cases(output),]
      }
    }
    massShift <- as.data.frame(matrix(ncol = length(Shiftlist), nrow = 1))
    rtShift <- as.data.frame(matrix(ncol = length(Shiftlist), nrow = 1))
    massShift <- AlignmentT1[,seq(1, 3*length(Shiftlist)-2 ,3)]
    for (i in 1:nrow(massShift)){
      massShiftALL[i] <- max(massShift[i,]) - min(massShift[i,])
    }
    rtShift <- AlignmentT1[,seq(2, 3*length(Shiftlist)-1 ,3)]
    for (i in 1:nrow(rtShift)){
      rtShiftALL[i] <- max(rtShift[i,]) - min(rtShift[i,])
    }
  }
  # plot the distribution of the universal parameters
  noiselevel <- noiselevel[!is.na(noiselevel)]
  noiselevel <- noiselevel[order(noiselevel)]
  noiselevel <- noiselevel[1:round(length(noiselevel)*0.97)]
  ppm2D <- ppm2D[complete.cases(ppm2D),]
  ppm2D <- ppm2D[order(ppm2D[,3]),]
  mzDiff2D <- mzDiff2D[complete.cases(mzDiff2D),]
  mzDiff2D <- mzDiff2D[order(mzDiff2D[,3]),]
  mzDiff2D <- mzDiff2D[1:round(nrow(mzDiff2D)*0.97),]
  peakWidth <- peakWidth[!is.na(peakWidth)]
  peakWidth <- peakWidth[order(peakWidth)]
  peakWidth <- peakWidth[1:round(length(peakWidth)*0.97)]
  peakScans <- peakScans[!is.na(peakScans)]
  peakScans <- peakScans[order(peakScans)]
  peakScans <- peakScans[1:round(length(peakScans)*0.97)]
  SNRatio <- SNRatio[!is.na(SNRatio)]
  SNRatio <- SNRatio[order(-SNRatio)]
  SNRatio <- SNRatio[1:round(length(SNRatio)*0.97)]
  peakHeight <- peakHeight[!is.na(peakHeight)]
  peakHeight <- peakHeight[order(-peakHeight)]
  peakHeight <- peakHeight[1:round(length(peakHeight)*0.97)]
  if (length(filename) > 1) {
    massShiftALL <- massShiftALL[!is.na(massShiftALL)]
    massShiftALL <- massShiftALL[order(massShiftALL)]
    massShiftALL <- massShiftALL[1:round(length(massShiftALL)*0.97)]
    rtShiftALL <- rtShiftALL[!is.na(rtShiftALL)]
    rtShiftALL <- rtShiftALL[order(rtShiftALL)]
    rtShiftALL <- rtShiftALL[1:round(length(rtShiftALL)*0.97)]
    maxmassshift <- max(massShiftALL)
    maxrtshift <- max(rtShiftALL)
  }
  maxppm <- max(ppm2D[,3])
  maxppm <- ceiling(maxppm)
  maxmzdiff <- max(mzDiff2D[,3])
  maxmzdiff <- (ceiling(maxmzdiff*100))/100
  minnoise <- min(noiselevel)
  minnoise <- floor(minnoise)
  W <- mean(peakWidth, trim=0.05, na.rm = TRUE)
  H <- mean(peakHeight, trim=0.05, na.rm = TRUE)
  ratio <- H/W
  minpeakwidth <- min(peakWidth)
  maxpeakwidth <- max(peakWidth)
  if (maxpeakwidth > 35 & ratio > 515) {
    minpeakwidth <- 0
    maxpeakwidth <- (ceiling(maxpeakwidth)+7)/2
  } else {
    minpeakwidth <- (ceiling(minpeakwidth))+4
    maxpeakwidth <- ceiling(maxpeakwidth)+5
  }
  minpeakscan <- min(peakScans)
  minpeakscan <- floor(minpeakscan)
  maxpeakscan <- max(peakScans)
  maxpeakscan <- floor(maxpeakscan)
  minSN <- min(SNRatio)
  if (minSN < 3){
    minSN <- 3
  }
  minpeakheight <- min(peakHeight)
  minpeakheight <- floor(minpeakheight)
  ##> generate plot
  if (length(filename) > 1) {
    XCMSparameters = data.frame(
      para = c("ppm","p_min","p_max","snthresh","mzdiff","integrate","pre_left","pre_right","noise","bw","min_fraction","mzwid","minsamp","max"),
      desc = c("ppm", "peakwidth min", "peakwidth max", "signal/noise threshold (snthresh)", "mzdiff", "integrate",
               "prefilter peaks", "prefilter intensity", "noise","bw", "min_fraction", "mzwid", "minsamp", "max"),
      Value = c(maxppm, minpeakwidth, maxpeakwidth, minSN, -0.01, 1, minpeakscan, minnoise, minnoise, 5, 0.5, maxmassshift, 1, 100)
    )
  } else {
    XCMSparameters = data.frame(
      para = c("ppm","p_min","p_max","snthresh","mzdiff","integrate","pre_left","pre_right","noise"),
      desc = c("ppm", "peakwidth min", "peakwidth max", "signal/noise threshold (snthresh)", "mzdiff", "integrate",
               "prefilter peaks", "prefilter intensity", "noise"),
      Value = c(maxppm, minpeakwidth, maxpeakwidth, minSN, -0.01, 1, minpeakscan, minnoise, minnoise)
    )
  }
  return(XCMSparameters)
  print(Sys.time() - start_time)
  message("All finish")
}
